b="HeisSureshGopi"
print(b[:5])
print(b[2:])
print(b[2:5])
print(b[-5:-2])
print(b.upper())
print(b.lower())
print(b.strip())
print(b.replace("H","J"))
print(b.split(" "))
print(b.capitalize())
print(b.casefold())
print(b.center(50))
print(b.count("s"))
print(b.encode('ascii'))
print(b.endswith(" "))
print(b.expandtabs(2))
print(b.find("s"))
#print(b.format("s")) # ...
#print(b.format_map())#...
print(b.index("Suresh"))
print(b.isalnum())
print(b.isalpha())
print(b.isascii())
print()